### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by karthiclodpi** [lorabasics/lorabasicsmodem#2]
Hi @matthieuantoine 

I am trying work on 2.4Ghz lorawan,

Node : https://www.semtech.com/products/wireless-rf/lora-transceivers/sx1280ed1zhp
Gateway :  https://www.semtech.com/products/wireless-rf/lora-gateways/sx1280zxxxxgw1

`make modem_2_4` and got `soft_modem_2g4.bin` , flashed it to nucleo l073 + sx1280ed1zhp (via ST-Link). Node is not joining and not even getting any serial log.

Plz assist

Thanks

**Comment by matthieuantoine** [comment]
Hi, did you try to use debug mode and see where the program is blocked?

**Comment by karthiclodpi** [comment]
Hi @matthieuantoine 

Tried setting up OpenOCD for debugging. But unsuccessful.

Do you have a document for setting up the debugger option

Thanks
KarthiG

**Comment by karthiclodpi** [comment]
Hi @matthieuantoine ,

Working, Issue was with my ST- Board, Yet to set OpenOCD for debugging

Thanks
